### ISSUE TITLE
Upgrading to Angular 9

### ISSUE THREAD

**Issue by prindacerk** [sahilpurav/ngx-serverless-starter#1]
Would it be possible for you to upgrade this to Angular 9 and use Ivy? I'm having problems when I try to upgrade myself. There's no webpack involved anymore and Angular is using Typescript so I may be missing something.

Would be great if you can upgrade this project to Angular 9 so a newcomer can follow it without issues.

**Comment by prindacerk** [comment]
Tried updating the application but it doesn't seem to work. Would be great if you can upgrade this properly.

**Comment by sahilpurav** [comment]
@prindacerk Updated starter to support Angular v10.
