### ISSUE TITLE
Routing is not working

### ISSUE THREAD

**Issue by webhacking** [sahilpurav/ngx-serverless-starter#2]
Hi, i'm trying to angular ssr with this repo.
But is not working when i move another path app give me a blank page

**Comment by sahilpurav** [comment]
@webhacking  - Please try with the latest version. I don't think of supporting lesser version than Angular 10.

**Comment by sahilpurav** [comment]
@webhacking  - I've updated the code. Now you won't require to add "/dev" while running the application on local. This is fixed with following command:

`serverless offline start --noPrependStageInUrl`

This will also ensure internal Angular routings are working fine.
