### ISSUE TITLE
Assets are not being loaded. 

### ISSUE THREAD

**Issue by nirmpate** [sahilpurav/ngx-serverless-starter#3]
Hello,

I am trying to learn and understand setting up Angular Universal using AWS Lambda.  I noticed that when trying to run either serverless offline or deploying the app to Lambda, the assets such as styles.css, main.js are returning 404 Not Found.  How can we make these files available to the app using Lambda? 

<img width="1792" alt="Screen Shot 2020-08-04 at 10 37 32 PM" src="https://user-images.githubusercontent.com/17192239/89369243-28c16e00-d6a3-11ea-8389-8dae49865914.png">

**Comment by nirmpate** [comment]
I figured it out. Since the application is hosted on /dev we need the application to have   <base href="/dev/">.  This is possible by changing your build to 

    "build:sls": "ng build --prod --base-href /dev/ && ng run ngx-serverless-starter:serverless:production",

**Comment by sahilpurav** [comment]
@nirmpate - This wouldn't be the case of production since you're going to have it behind the domain which will not have "/dev/" at the end.

**Comment by sahilpurav** [comment]
@nirmpate - I've updated the code. Now you won't require to add "/dev" while running the application on local.
