### ISSUE TITLE
upgrade aws-serverless-express to @vendia/serverless-express

### ISSUE THREAD

**Issue by byungjuJin** [sahilpurav/ngx-serverless-starter#6]
They (aws-serverless-express) are rebranded from aws-serverless-express to @vendia/serverless-express
and also api moves a bit.

Please check below

https://github.com/vendia/serverless-express/blob/mainline/UPGRADE.md

**Comment by sahilpurav** [comment]
@byungjuJin Thanks for opening the issue. I will update the repository and make a new release.

**Comment by sahilpurav** [comment]
@byungjuJin Deprecated package is removed and replaced.
